import { useState, useCallback } from "react";
import { matches } from "@/data/matches";
import MatchCard from "@/components/MatchCard";
import AccaBuilder from "@/components/AccaBuilder";
import { SimulationResult } from "@/lib/simulation";

export default function Home() {
  const [results, setResults] = useState<Record<number, SimulationResult>>({});

  const handleResult = useCallback((matchId: number, result: SimulationResult) => {
    setResults((prev) => ({ ...prev, [matchId]: result }));
  }, []);

  return (
    <div className="min-h-screen bg-[#080f17] flex flex-col">
      {/* Header */}
      <div className="bg-[#0d1e2e] border-b border-white/8 sticky top-0 z-10 backdrop-blur-sm">
        <div className="max-w-2xl mx-auto px-4 py-4 flex items-center gap-3">
          <div className="w-8 h-8 bg-emerald-500 rounded-lg flex items-center justify-center shrink-0">
            <svg className="w-4 h-4 text-white" fill="none" viewBox="0 0 24 24" stroke="currentColor">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 19v-6a2 2 0 00-2-2H5a2 2 0 00-2 2v6a2 2 0 002 2h2a2 2 0 002-2zm0 0V9a2 2 0 012-2h2a2 2 0 012 2v10m-6 0a2 2 0 002 2h2a2 2 0 002-2m0 0V5a2 2 0 012-2h2a2 2 0 012 2v14a2 2 0 01-2 2h-2a2 2 0 01-2-2z" />
            </svg>
          </div>
          <div>
            <h1 className="text-white font-black text-base leading-none">Match Simulator</h1>
            <p className="text-white/30 text-[10px] mt-0.5">Monte Carlo · Poisson Model · 40k iterations</p>
          </div>
          <div className="ml-auto text-right">
            <div className="text-emerald-400 text-[10px] font-semibold uppercase tracking-widest">Slovensko 1. liga</div>
            <div className="text-white/30 text-[10px]">SOB. 16.05 · 17:00</div>
          </div>
        </div>
      </div>

      {/* Scrollable content */}
      <div className="flex-1 overflow-y-auto pb-2">
        {/* Disclaimer */}
        <div className="max-w-2xl mx-auto px-4 pt-4">
          <div className="bg-amber-500/8 border border-amber-500/15 rounded-xl px-4 py-2.5 flex items-start gap-2">
            <svg className="w-3.5 h-3.5 text-amber-400 mt-0.5 shrink-0" fill="none" viewBox="0 0 24 24" stroke="currentColor">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M13 16h-1v-4h-1m1-4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z" />
            </svg>
            <p className="text-amber-400/70 text-[10px] leading-relaxed">
              Predictions are generated by a Poisson-based Monte Carlo model using bookmaker odds as input. For informational purposes only. Gambling involves risk.
            </p>
          </div>
        </div>

        {/* Match Cards */}
        <div className="max-w-2xl mx-auto px-4 py-5 space-y-4">
          {matches.map((match) => (
            <MatchCard key={match.id} match={match} onResult={handleResult} />
          ))}
        </div>
      </div>

      {/* Sticky Accumulator Builder */}
      <AccaBuilder results={results} />
    </div>
  );
}
